// lib/client/burn/telemetry.ts — typed telemetry event constructors (Axes 2–3).
//
// PRIVACY INVARIANT: every event type has an explicit whitelist of allowed fields
// (additionalProperties: false). Forbidden categories include: raw content,
// file paths, error messages, stack traces, salts, model/session internals, and
// bearer/identity secrets — the per-handle CLAIM token (lib/client/burn/
// claimToken.ts), the collector nonce, and any API key. The claim token is a
// bearer secret for identity (spec §2.10): it must NEVER reach an analytics or
// error-capture payload. The typed constructors below are the only event source
// and none accept a token, but FORBIDDEN_KEY_RE names them too as defence in depth.
//
// session_id is a telemetry-only random ID generated by this module.
// It must NEVER be derived from log files, file names, or the Claude/Codex
// session_id. It is stored in sessionStorage (tab lifetime only) so it cannot
// accumulate into a permanent user identity.
//
// 4 event types (from codex-r4-meta-privacy.md):
//   auto_detect_started    — FSA flow begins
//   auto_detect_completed  — upload accepted
//   auto_detect_failed     — user abandoned or error occurred
//   survey_responded       — post-upload survey answer

// ── Types ─────────────────────────────────────────────────────────────────────

export type DurationBucket = "0-1m" | "1-3m" | "3-5m" | "5-10m" | "10-20m" | "20m+";

export type AutoDetectResult = "summary_generated" | "upload_accepted";

export type FailureCode =
  | "fsa_unavailable"
  | "folder_rejected"
  | "permission_denied"
  | "no_supported_logs"
  | "parse_failed"
  | "summary_validation_failed"
  | "upload_failed"
  | "unknown";

export type FailureStage =
  | "capability_check"
  | "folder_picker"
  | "scan"
  | "parse"
  | "validate"
  | "upload";

export type HardestStep =
  | "terminal_setup"
  | "folder_selection"
  | "browser_permission"
  | "upload"
  | "understanding_results"
  | "other_predefined";

// Only YYYY-MM-DD (not a full timestamp — no time information that could
// correlate to a specific log entry).
type WeekKey = string;

interface BaseEvent {
  readonly event: string;
  readonly schemaVersion: 1;
  readonly weekKey: WeekKey;
  readonly session_id: string;
}

export interface AutoDetectStartedEvent extends BaseEvent {
  readonly event: "auto_detect_started";
  readonly fsaSupported: boolean;
}

export interface AutoDetectCompletedEvent extends BaseEvent {
  readonly event: "auto_detect_completed";
  readonly durationBucket: DurationBucket;
  readonly result: AutoDetectResult;
}

export interface AutoDetectFailedEvent extends BaseEvent {
  readonly event: "auto_detect_failed";
  readonly durationBucket: DurationBucket;
  readonly failureCode: FailureCode;
  readonly failureStage: FailureStage;
}

export interface SurveyRespondedEvent extends BaseEvent {
  readonly event: "survey_responded";
  readonly hardestStep: HardestStep;
  readonly setupTimeBucket: DurationBucket;
}

export type TelemetryEvent =
  | AutoDetectStartedEvent
  | AutoDetectCompletedEvent
  | AutoDetectFailedEvent
  | SurveyRespondedEvent;

// ── Session ID ────────────────────────────────────────────────────────────────

const SESSION_KEY = "cl_telemetry_session_id";

// Returns a telemetry-only session ID (128-bit random hex) scoped to the
// current browser tab (sessionStorage). A new tab gets a new ID.
function getOrCreateSessionId(): string {
  if (typeof sessionStorage === "undefined") return generateSessionId();
  let id = sessionStorage.getItem(SESSION_KEY);
  if (!id || !/^[a-f0-9]{32}$/.test(id)) {
    id = generateSessionId();
    sessionStorage.setItem(SESSION_KEY, id);
  }
  return id;
}

function generateSessionId(): string {
  const buf = new Uint8Array(16);
  if (typeof crypto !== "undefined" && crypto.getRandomValues) {
    crypto.getRandomValues(buf);
  } else {
    // Node.js fallback (tests)
    for (let i = 0; i < 16; i++) buf[i] = Math.floor(Math.random() * 256);
  }
  return Array.from(buf).map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ── Week key ─────────────────────────────────────────────────────────────────

function todayWeekKey(): string {
  const now = new Date();
  const y = now.getUTCFullYear().toString().padStart(4, "0");
  const m = (now.getUTCMonth() + 1).toString().padStart(2, "0");
  const d = now.getUTCDate().toString().padStart(2, "0");
  return `${y}-${m}-${d}`;
}

// ── Typed constructors ────────────────────────────────────────────────────────

// These are the ONLY way to create telemetry events. Using object spread
// ({ ...err, ...context }) is forbidden — it can leak arbitrary properties.

export function makeAutoDetectStartedEvent(fsaSupported: boolean): AutoDetectStartedEvent {
  return {
    event: "auto_detect_started",
    schemaVersion: 1,
    weekKey: todayWeekKey(),
    session_id: getOrCreateSessionId(),
    fsaSupported,
  };
}

export function makeAutoDetectCompletedEvent(
  durationBucket: DurationBucket,
  result: AutoDetectResult,
): AutoDetectCompletedEvent {
  return {
    event: "auto_detect_completed",
    schemaVersion: 1,
    weekKey: todayWeekKey(),
    session_id: getOrCreateSessionId(),
    durationBucket,
    result,
  };
}

export function makeAutoDetectFailedEvent(
  durationBucket: DurationBucket,
  failureCode: FailureCode,
  failureStage: FailureStage,
): AutoDetectFailedEvent {
  return {
    event: "auto_detect_failed",
    schemaVersion: 1,
    weekKey: todayWeekKey(),
    session_id: getOrCreateSessionId(),
    durationBucket,
    failureCode,
    failureStage,
  };
}

export function makeSurveyRespondedEvent(
  hardestStep: HardestStep,
  setupTimeBucket: DurationBucket,
): SurveyRespondedEvent {
  return {
    event: "survey_responded",
    schemaVersion: 1,
    weekKey: todayWeekKey(),
    session_id: getOrCreateSessionId(),
    hardestStep,
    setupTimeBucket,
  };
}

// ── Validation (used by both client + server test) ────────────────────────────

// Allowed fields per event type. Any key not in these lists is forbidden.
const BASE_KEYS = ["event", "schemaVersion", "weekKey", "session_id"];

const ALLOWED_KEYS: Record<string, string[]> = {
  auto_detect_started: [...BASE_KEYS, "fsaSupported"],
  auto_detect_completed: [...BASE_KEYS, "durationBucket", "result"],
  auto_detect_failed: [...BASE_KEYS, "durationBucket", "failureCode", "failureStage"],
  survey_responded: [...BASE_KEYS, "hardestStep", "setupTimeBucket"],
};

// Fields that must NEVER appear in any telemetry payload (privacy invariant).
// This regex matches any key that could carry raw content, paths, or secrets —
// including bearer/identity secrets (claimToken, token, bearer, authorization,
// nonce, apiKey, secret, credential): the claim token is body-only and banned
// from telemetry/analytics/error-capture (spec §2.10). None of these collide
// with an allowed key, and the forbidden check runs before the whitelist check.
const FORBIDDEN_KEY_RE =
  /^(content|message|prompt|response|completion|input|output|code|payload|payloadText|requestBody|rawBody|json|jsonl|rawLine|jsonlLine|line|firstLine|lastLine|path|folderPath|rootPath|cwd|projectName|repoName|fileName|directory|selectedDirectory|sample|preview|snippet|errorContext|offendingRecord|record|entry|error|exception|stack|cause|salt|deviceSalt|projectHashInput|projectSlug|hashPreimage|claimToken|claim|token|bearer|authorization|auth|secret|nonce|apiKey|apikey|credential|credentials|metadata|properties|context|extra|debug|userAgent|sessionId)$/i;

const DURATION_BUCKETS: DurationBucket[] = ["0-1m", "1-3m", "3-5m", "5-10m", "10-20m", "20m+"];
const DETECT_RESULTS: AutoDetectResult[] = ["summary_generated", "upload_accepted"];
const FAILURE_CODES: FailureCode[] = [
  "fsa_unavailable", "folder_rejected", "permission_denied",
  "no_supported_logs", "parse_failed", "summary_validation_failed",
  "upload_failed", "unknown",
];
const FAILURE_STAGES: FailureStage[] = [
  "capability_check", "folder_picker", "scan", "parse", "validate", "upload",
];
const HARDEST_STEPS: HardestStep[] = [
  "terminal_setup", "folder_selection", "browser_permission",
  "upload", "understanding_results", "other_predefined",
];

// session_id regex: 32 lowercase hex chars (128-bit random)
const SESSION_ID_RE = /^[a-f0-9]{32}$/;
// weekKey: YYYY-MM-DD
const WEEK_KEY_RE = /^\d{4}-\d{2}-\d{2}$/;

export type ValidationResult =
  | { ok: true; event: TelemetryEvent }
  | { ok: false; error: string };

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

// Validates a raw (potentially untrusted) payload against the telemetry schema.
// Returns ok:true + the typed event, or ok:false + an error string.
// This is the single source of truth for both client-side and server-side checks.
export function validateTelemetryEvent(raw: unknown): ValidationResult {
  if (!isPlainObject(raw)) return { ok: false, error: "Event must be a JSON object." };

  // Check for forbidden keys first (privacy gate)
  for (const k of Object.keys(raw)) {
    if (FORBIDDEN_KEY_RE.test(k)) {
      return { ok: false, error: `Forbidden field: "${k}"` };
    }
  }

  const eventType = raw["event"];
  if (typeof eventType !== "string" || !(eventType in ALLOWED_KEYS)) {
    return { ok: false, error: `Unknown event type: "${eventType}"` };
  }

  // Enforce no extra keys beyond the allowed list for this event type
  const allowed = ALLOWED_KEYS[eventType];
  for (const k of Object.keys(raw)) {
    if (!allowed.includes(k)) {
      return { ok: false, error: `Unexpected field "${k}" for event "${eventType}"` };
    }
  }

  if (raw["schemaVersion"] !== 1) {
    return { ok: false, error: "schemaVersion must be 1" };
  }
  if (typeof raw["weekKey"] !== "string" || !WEEK_KEY_RE.test(raw["weekKey"] as string)) {
    return { ok: false, error: "weekKey must be YYYY-MM-DD" };
  }
  if (typeof raw["session_id"] !== "string" || !SESSION_ID_RE.test(raw["session_id"] as string)) {
    return { ok: false, error: "session_id must be 32 lowercase hex chars" };
  }

  switch (eventType) {
    case "auto_detect_started":
      if (typeof raw["fsaSupported"] !== "boolean") {
        return { ok: false, error: "auto_detect_started.fsaSupported must be boolean" };
      }
      break;
    case "auto_detect_completed":
      if (!DURATION_BUCKETS.includes(raw["durationBucket"] as DurationBucket)) {
        return { ok: false, error: "auto_detect_completed.durationBucket is invalid" };
      }
      if (!DETECT_RESULTS.includes(raw["result"] as AutoDetectResult)) {
        return { ok: false, error: "auto_detect_completed.result is invalid" };
      }
      break;
    case "auto_detect_failed":
      if (!DURATION_BUCKETS.includes(raw["durationBucket"] as DurationBucket)) {
        return { ok: false, error: "auto_detect_failed.durationBucket is invalid" };
      }
      if (!FAILURE_CODES.includes(raw["failureCode"] as FailureCode)) {
        return { ok: false, error: "auto_detect_failed.failureCode is invalid" };
      }
      if (!FAILURE_STAGES.includes(raw["failureStage"] as FailureStage)) {
        return { ok: false, error: "auto_detect_failed.failureStage is invalid" };
      }
      break;
    case "survey_responded":
      if (!HARDEST_STEPS.includes(raw["hardestStep"] as HardestStep)) {
        return { ok: false, error: "survey_responded.hardestStep is invalid" };
      }
      if (!DURATION_BUCKETS.includes(raw["setupTimeBucket"] as DurationBucket)) {
        return { ok: false, error: "survey_responded.setupTimeBucket is invalid" };
      }
      break;
  }

  return { ok: true, event: raw as unknown as TelemetryEvent };
}

// ── Client send helper ────────────────────────────────────────────────────────

// Sends a telemetry event to the server. Fire-and-forget: errors are silently
// swallowed so that a telemetry failure never disrupts the main flow.
//
// sendBeacon is intentionally NOT used here: sendBeacon cannot attach custom
// Authorization headers, which are required for the HMAC collector token.
// fetch with keepalive: true provides equivalent unload-survival semantics.
export function sendTelemetryEvent(event: TelemetryEvent): void {
  // Validate locally before sending (defence in depth).
  const result = validateTelemetryEvent(event);
  if (!result.ok) return; // drop silently

  void (async () => {
    try {
      const body = JSON.stringify(event);
      // Fetch a single-use token bound to this telemetry POST.
      const tokenRes = await fetch("/api/internal/issue-collector-token", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind: "telemetry" }),
      });
      if (!tokenRes.ok) return; // drop silently if token issuance fails
      const tokenData = (await tokenRes.json()) as { token?: string };
      if (!tokenData.token) return;

      fetch("/api/telemetry/auto-detect", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${tokenData.token}`,
        },
        body,
        keepalive: true,
      }).catch(() => {});
    } catch {
      // Never throw from telemetry
    }
  })();
}

// ── Duration timer ────────────────────────────────────────────────────────────

// Returns a function that, when called, returns the elapsed DurationBucket.
export function startDurationTimer(): () => DurationBucket {
  const start = Date.now();
  return (): DurationBucket => {
    const ms = Date.now() - start;
    const min = ms / 60_000;
    if (min < 1) return "0-1m";
    if (min < 3) return "1-3m";
    if (min < 5) return "3-5m";
    if (min < 10) return "5-10m";
    if (min < 20) return "10-20m";
    return "20m+";
  };
}
