#!/usr/bin/env node
// codegen-pricing.mjs — emit pricing.generated.ts from the single source of truth.
//
// Reads tools/usage-poc/model-pricing.json (consumed by the Python collector) and
// writes lib/client/burn/pricing.generated.ts. The browser-side collector port
// must NEVER fetch pricing live — that would create a second source of truth
// and let a tampered response inflate cost estimates. Build-time codegen keeps
// Python and TS pricing byte-identical from one file.
//
// Run with: node scripts/codegen-pricing.mjs

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const SRC = resolve(repoRoot, "tools/usage-poc/model-pricing.json");
const OUT = resolve(repoRoot, "lib/client/burn/pricing.generated.ts");

const raw = JSON.parse(readFileSync(SRC, "utf-8"));

if (typeof raw._pricing_as_of !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(raw._pricing_as_of)) {
  throw new Error(`model-pricing.json missing valid _pricing_as_of (got ${raw._pricing_as_of})`);
}
if (!raw.claude || typeof raw.claude !== "object") throw new Error("missing claude section");
if (!raw.codex || typeof raw.codex !== "object") throw new Error("missing codex section");
if (!raw.claude._default) throw new Error("claude._default missing");
if (!raw.codex._default) throw new Error("codex._default missing");

// Strip leading-underscore meta keys when copying the pricing dictionaries.
// _pricing_as_of / _note / _match / _source are documentation; only model
// entries plus _default are emitted (we serialize _default explicitly).
function pickPricing(obj, requiredKeys) {
  const out = {};
  for (const [name, rate] of Object.entries(obj)) {
    if (name.startsWith("_") && name !== "_default") continue;
    if (typeof rate !== "object" || rate === null) {
      throw new Error(`pricing entry ${name} is not an object`);
    }
    for (const k of requiredKeys) {
      if (typeof rate[k] !== "number") {
        throw new Error(`pricing entry ${name} missing numeric ${k}`);
      }
    }
    out[name] = rate;
  }
  return out;
}

const CLAUDE_KEYS = ["input", "output", "cache_read", "cache_write_5m", "cache_write_1h"];
const CODEX_KEYS = ["input", "cached_input", "output"];

const claudePricing = pickPricing(raw.claude, CLAUDE_KEYS);
const codexPricing = pickPricing(raw.codex, CODEX_KEYS);

const PRICING_AS_OF = raw._pricing_as_of;

const banner = [
  "// AUTO-GENERATED by scripts/codegen-pricing.mjs from tools/usage-poc/model-pricing.json.",
  "// DO NOT EDIT. Re-run `node scripts/codegen-pricing.mjs` after editing the JSON.",
  "//",
  "// USD per 1M tokens. Browser-side cost estimation MUST use this table — live fetch",
  "// would create a second source of truth and let a tampered response inflate costs.",
  "",
].join("\n");

const body = `export const PRICING_AS_OF = ${JSON.stringify(PRICING_AS_OF)} as const;

export interface ClaudeRate {
  input: number;
  output: number;
  cache_read: number;
  cache_write_5m: number;
  cache_write_1h: number;
}

export interface CodexRate {
  input: number;
  cached_input: number;
  output: number;
}

export interface PricingTable {
  claude: Record<string, ClaudeRate> & { _default: ClaudeRate };
  codex: Record<string, CodexRate> & { _default: CodexRate };
}

export const MODEL_PRICING: PricingTable = ${JSON.stringify(
  { claude: claudePricing, codex: codexPricing },
  null,
  2,
)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, banner + body, "utf-8");
console.log(`codegen-pricing → ${OUT} (${PRICING_AS_OF})`);
